### ISSUE TITLE
Doesn't work with KubeJS 6.1

### ISSUE THREAD

**Issue by aaronhowser1** [tom5454/Create-Ore-Excavation#44]
script: https://gist.github.com/aaronhowser1/809928f5fc22cfd98216bb59f55f1abb

![image](https://github.com/tom5454/Create-Ore-Excavation/assets/15698722/b03f72e8-f06d-4301-8c06-e8660a7c2f5b)

```
[05:01:59] [ERROR] ! server_scripts:recipes/create_ore_excavation.js:10: Failed to create recipe for type 'createoreexcavation:drilling': Constructor for createoreexcavation:drilling with 4 arguments not found!
[05:02:00] [ERROR] ! #10: Error occurred while handling event 'ServerEvents.recipes': TypeError: Cannot find function biomeWhitelist in object <no id> [null]. (server_scripts:recipes/create_ore_excavation.js#10)
```
