### ISSUE TITLE
KubeJS sample does not work in MC 1.21.1

### ISSUE THREAD

**Issue by idiosync** [tom5454/Create-Ore-Excavation#143]
When trying the Sample KubeJS for 1.20 in 1.21.1 It does not work. can we please get a sample that works in 1.21.1? 

[KubeJS Server/]: server_scripts:CreatOreExcav.js#10: Failed to create a 'createoreexcavation:vein' recipe from args [{"text": "My redstone vein"}, minecraft:redstone]: Constructor for createoreexcavation:vein with 2 arguments not found!
[KubeJS Server/]: CreatOreExcav.js#10: Error in 'ServerEvents.recipes': dev.latvian.mods.rhino.EcmaError: TypeError: Cannot find function placement in object createoreexcavation:kjs/3kkgyrgdo34mqk3sfjq4b8a1p[createoreexcavation:vein].

Using KubeJS 2101.7.1-build.181
Using createoreexcavation-1.21-1.6.2

**Comment by tom5454** [comment]
1.21 doesn't have kubejs api support yet
https://github.com/tom5454/Create-Ore-Excavation/issues/138#issuecomment-2707161518.
